### ISSUE TITLE
Fails to build / test

### ISSUE THREAD

**Issue by demands** [goodeggs/bites#54]
Not sure what's going on here, but builds are failing with regularity:

```
[10:15:51] Bad link 404 http://localhost:8000/build/build/fonts/icons.eot from http://localhost:8000/build/kale-4e65212f.css

/Users/maxedmands/Projects/bites/gulpfile.coffee:101
        throw new Error(message);
              ^
Error: Bad link 404 http://localhost:8000/build/build/fonts/icons.eot from http://localhost:8000/build/kale-4e65212f.css
  at [object Object].<anonymous> (/Users/maxedmands/Projects/bites/gulpfile.coffee:83:19)
  at [object Object].emit (events.js:98:17)
  at [object Object].Crawler.handleResponse (/Users/maxedmands/Projects/bites/node_modules/simplecrawler/lib/crawler.js:940:10)
  at ClientRequest.<anonymous> (/Users/maxedmands/Projects/bites/node_modules/simplecrawler/lib/crawler.js:851:13)
  at ClientRequest.g (events.js:180:16)
  at ClientRequest.emit (events.js:95:17)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
  at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
  at Socket.socketOnData [as ondata] (http.js:1584:20)
  at TCP.onread (net.js:528:27)
```

**Comment by demands** [comment]
Oh, derp, this is because I had a dev server running on port 8000.
